# 使用国内镜像源的Python基础镜像

FROM python:3.10-slim

# 设置工作目录
WORKDIR /app

# 复制当前目录内容到工作目录
COPY . /app

# 安装Python依赖
RUN pip install --no-cache-dir -r requirements.txt

# 暴露Flask默认端口
EXPOSE 5000

# 设置环境变量
ENV FLASK_APP=app.py

# 运行Flask应用
CMD ["flask", "run", "--host=0.0.0.0"]